baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "anatole"

[params]
title = "I'm Jane Doe"
author = "asdf"
description = "Call me Jane"
profilePicture = "images/avatar.jpg"
googleFonts = [
  "Fruktur",
  "Indie+Flower",
  "Roboto:ital,wght@0,100;0,400;0,700;1,400"
]
customCss = ["css/custom.css"]

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
